### ISSUE TITLE
Tracking Issue: Scheddy 1.0

### ISSUE THREAD

**Issue by coredoesdev** [ZTL-ARTCC/scheddy#1]
**Description**
Develop an in-house scheduling system to replace Easy!Appointments and better meet the needs of our training system.

**Purpose**
Easy!Appointments is no longer meeting our needs, and is taking up too much web team time, and frustrating both mentors and students.

**Immediate Project Goals**
- [x] Meet all the needs of the ZTL training department
    - We have put together a survey with OK to figure out what it is our wonderful mentors actually want
- [x] Be a single, self-contained package that integrates with the website but is otherwise independent
- [x] Be customizable, to an extent

**Long-Term Project Goals**
- [x] Be a single package usable by other facilities around VATUSA and VATSIM as a whole

**Timeline/TODO**
- #3 
- #4 

**Blocking Issues/Discussion**
- None right now

**RFCs**
- #2 

More coming soon.
-TD

**Comment by coredoesdev** [comment]
It's all done!
